# Generated by Django 4.2.5 on 2023-10-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
