# Generated by Django 4.2.5 on 2023-11-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_income_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('transportation', 'Transportation')], max_length=100),
        ),
    ]
