# Generated by Django 4.2.5 on 2023-11-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('medicine', 'Medicine'), ('travel', 'Travel'), ('fees', 'Fees'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('transportation', 'Transportation')], max_length=100),
        ),
    ]
