# Generated by Django 4.2.5 on 2023-11-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0006_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('medicine', 'Medicine'), ('travel', 'Travel'), ('fees', 'Fees'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('clothing', 'Clothing'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('charity', 'Charity'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('salary', 'Salary'), ('bank', 'Bank'), ('freelance', 'Freelance Work'), ('business', 'Business Income'), ('investment', 'Investment Returns'), ('rental', 'Rental Income'), ('gift', 'Gift or Inheritance'), ('side_job', 'Side Job'), ('commission', 'Commission'), ('online_sales', 'Online Sales'), ('other', 'Other')], max_length=255),
        ),
    ]
