# Generated by Django 4.2.5 on 2023-11-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0008_banktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='category',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
