# Generated by Django 4.2.5 on 2023-11-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0009_remove_banktransaction_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='transaction_type',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('groceries', 'Groceries'), ('medicine', 'Medicine'), ('travel', 'Travel'), ('fees', 'Fees'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('clothing', 'Clothing'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('charity', 'Charity'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=100),
        ),
    ]
