# Generated by Django 4.2.5 on 2023-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0011_alter_expense_category_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
