# Generated by Django 4.2.5 on 2023-11-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0012_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
