# Generated by Django 4.2.5 on 2023-11-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0013_alter_income_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food/drink', 'Food/Drink'), ('groceries', 'Groceries'), ('health', 'Health'), ('travel', 'Travel'), ('rent/bills', 'Rent/Bills'), ('entertainment', 'Entertainment'), ('education', 'Education'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('salary', 'Salary'), ('bank', 'Bank'), ('investment', 'Investment Returns'), ('rental', 'Rental Income'), ('other', 'Other')], max_length=255),
        ),
    ]
